Add Publications
az-digitalag/group-website pull request #13
Opened 2020-08-07 18:04 UTC by dlebauer

adds publications section

2020-08-07 18:52 UTC, Chris-Schnaufer requested changes

2020-08-07 18:52 UTC, Chris-Schnaufer commented on content/publication/schnaufer-2020/index.md
> +abstract: "Unoccupied areal vehicles (UAVs or drones) are increasingly used in field research.
```suggestion
abstract: "Unoccupied arial vehicles (UAVs or drones) are increasingly used in field research.
```

2020-08-07 20:02 UTC, KristinaRiemer reviewed
This is really neat! I especially like the ability to filter publications by their type. 

I have thoughts on a couple aesthetic things. First, I'm not a fan of this weird alert thing at the top of the section and think it should be removed. 

![Screen Shot 2020-08-07 at 12 56 22 PM](https://user-images.githubusercontent.com/6686508/89683707-de600d00-d8ad-11ea-9b87-23c6c401d78c.png)

Second, I'm also not a fan of the little paper bullet points here, and I don't there needs to be any sort of bullet for the list of pubs. 

![Screen Shot 2020-08-07 at 12 58 09 PM](https://user-images.githubusercontent.com/6686508/89683779-08193400-d8ae-11ea-9051-5edcac1c942d.png)

I'm interested to hear others' opinions on these two matters. I'm happy to be the person to implement whatever changes we decide upon.

2020-08-07 22:27 UTC, Chris-Schnaufer commented
> ... not a fan of this weird alert thing ...

I'm not a fan either until I need them. If it could be changed into just the link `filtering publications` (or some text like that) I think it'd be better. For now it's OK as it is.

> ... little paper bullet points ...

Given the way the text is organized with the white space around each publication, I think the paper bullet points are not needed. If the blocks of text end up having white space within them, then the little paper bullet points should be there.

2020-08-10 13:57 UTC, KristinaRiemer commented
At the bottom of the publications section, there's this link "See All Publications" that leads to the same page as the alert's "filtering publications" link. 

<img width="1282" alt="Screen Shot 2020-08-10 at 6 54 46 AM" src="https://user-images.githubusercontent.com/6686508/89790239-7fc9a780-dad6-11ea-90cd-81b36b926526.png">

So those two links are redundant. We could make the "See All Publications" link to the top of the section and rename it something like "Filter and view all publications" or something?

2020-08-14 18:15 UTC, KristinaRiemer approved these changes

2020-08-14 18:17 UTC, merged